name: Build and Create Draft Release

on:
  push:
    branches:
      - main

jobs:
  build-and-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.20.1"

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

      - name: Create Draft Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: draft-build-${{ github.run_number }}
          releaseName: Draft Build # Adjust as desired
          draft: true
          artifacts: "build-artifacts" 
